name: Cypress CI Tests

on:
  # Manually trigger the workflow from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run start
          wait-on: 'http://localhost:3000'

      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Cypress-videos
          path: cypress/videos